version: '3.8'

services:
  vuls:
    build:
      context: .
      dockerfile: Dockerfile.debug
    command: ["server", "--listen", ":5515"]
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes


volumes:
  redis-data: